#!/bin/sh

config_load wol

config_get_bool enabled config enabled 0
[ $enabled -eq 0 ] && exit 0

config_get dest_intf config dest_intf "lan"
[ "$ACTION" = ifup -a "$INTERFACE" = $dest_intf ] || exit 0

config_get dest_ip config dest_ip

[ -n "$dest_ip" -a -n "$DEVICE" ] && {
    # Add route entry
    ip route add ${dest_ip}/32 dev $DEVICE
    # Add a static ARP spoofing entry
    ip neigh add $dest_ip lladdr ff:ff:ff:ff:ff:ff nud permanent dev $DEVICE
}
