#!/bin/sh /etc/rc.common
#set -x
START=20

kernel_ver="$(cat /proc/version | awk '{print $3}')"

uci2onoff() {
    case "$1" in
        0) echo "off";;
        1) echo "on";;
        *) echo "Invalid UCI enable option: $1" 1>&2; echo "on";;
    esac
}

setup_eee() {
    config_get eee ethernet eee 1
    pwrctl config --eee `uci2onoff $eee`
}

setup_autogreeen() {
    config_get autogreeen ethernet autogreeen 1
    pwrctl config --autogreeen `uci2onoff $autogreeen`
}

setup_ethapd() {
    config_get ethapd ethernet ethapd 1
    pwrctl config --ethapd `uci2onoff $ethapd`
}

setup_wait() {
    config_get wait cpu wait 1
    pwrctl config --wait `uci2onoff $wait`
}

setup_cpuspeed() {
    config_get cpuspeed cpu cpuspeed
    pwrctl config --cpuspeed $cpuspeed
}

move_irq_interrupts_cpu1() {
	#This cause crash on kernel 4.1 so only apply to kernel 3.4
	if [ -z "${kernel_ver##3.4*}" ]; then
		echo 2 > /proc/irq/72/smp_affinity
		echo 2 > /proc/irq/92/smp_affinity
		echo 2 > /proc/irq/98/smp_affinity
	fi
}

setup() {
    config_load power
    setup_autogreeen
    setup_eee
    setup_ethapd
    setup_wait
    setup_cpuspeed
	move_irq_interrupts_cpu1
}

start() {
    setup
}


