#!/bin/sh

upperdir=$1
overlay_bank=/overlay/bank_2

preserve_list="/etc/init.d/rootdevice /etc/rc.d/S94rootdevice /usr/sbin/random_seed /sbin/mount_root-mod /lib/mount_modroot/04_move_overlay /lib/mount_modroot/05_transfer_basefiles"

update_file_if_needed() { # <file> <source> <dest>
    cmp -s $2$1 $3$1 || cp -a $2$1 $3$1
}

for f in $preserve_list; do
    mkdir -p $overlay_bank$(dirname $f)
    update_file_if_needed $f $upperdir $overlay_bank
done
