#!/bin/sh

upperdir=$1
overlay_bank=/overlay/bank_2

move_overlay() {
  #use the config folder as check to know that we should populate the modoverlay (mtd3) and cleanup real overlay (mtd2)
  if [ -d $overlay_bank/etc/config ]; then

    #copy all file from overlay_bank to modoverlay keeping all attributes and links
    cp -a $overlay_bank/* $upperdir/

    #at this point we should remove all empty folders in bank_2 overlay, except the modoverlay mountpoint
    for f in "$overlay_bank/"*; do
      [ "$f" != "$overlay_bank$upperdir" ] && rm -rf "$f"
    done

  fi
}

preserve_files(){
  #these files should be moved back to bank_2 overlay to allow our mount hook to take place (and preserve root after boot)
  preserve_list="/etc/init.d/rootdevice /etc/rc.d/S94rootdevice /usr/sbin/random_seed /usr/sbin/mount_modoverlay /sbin/mount_root-mod /lib/mount_modroot/05_transfer_basefiles"

  update_file_if_needed() { # <file> <source> <dest>
    cmp -s "$2$1" "$3$1" || cp -a "$2$1" "$3$1"
  }

  for f in $preserve_list; do
    mkdir -p $overlay_bank$(dirname "$f")
    update_file_if_needed "$f" "$upperdir" $overlay_bank
  done
}

{ move_overlay; preserve_files; }
