#!/bin/sh /etc/rc.common

START=99
STOP=19
USE_PROCD=1

start_service()
{
	procd_open_instance
	procd_set_param command /sbin/trafficmon.lua
	procd_set_param respawn
	procd_set_param pidfile /var/run/trafficmon.pid
	procd_close_instance
}

stop_service()
{
	if [ -d /tmp/trafficmon ]; then
		rm -r /tmp/trafficmon
	fi
}