#!/bin/sh /etc/rc.common

#
# Launch process to help maintain dynamic pinholerules mapping values in
# /var/state/firewall
#

START=99
STOP=19
USE_PROCD=1

start_service()
{
	procd_open_instance
	procd_set_param command /sbin/trafficdata.lua
	procd_set_param respawn
	procd_set_param pidfile /var/run/trafficdata.pid
	procd_close_instance
}
