#!/bin/sh /etc/rc.common

START=65

USE_PROCD=1

start_service() {
	local _ENABLED=$(uci_get mobiled device_defaults enabled "1")
	if [ "$_ENABLED" = "1" ]; then
		PID=$(pgrep -f /usr/bin/mobiled)
		if [ -n "$PID" ]; then
			echo "Delaying Mobiled startup. Waiting for $PID to terminate"
			while kill -0 "$PID"; do
				sleep 1
			done
		fi

		logger -t mobiled "Starting Mobiled"
		procd_open_instance
		procd_set_param command /usr/bin/mobiled.sh
		procd_set_param respawn
		procd_close_instance
	else
		logger -t mobiled "Mobiled disabled"
	fi
}

service_triggers() {
	procd_add_reload_trigger "mobiled"
}

reload_service() {
	if $(pgrep -f /usr/bin/mobiled) ; then
		kill -s HUP $(pgrep -f /usr/bin/mobiled)
	fi
}

stop_service() {
	if $(pgrep -f /usr/bin/mobiled) ; then
		kill -s HUP $(pgrep -f /usr/bin/mobiled)
	fi
}
