#!/bin/sh

# tch-nginx-gui policy: override stock sysupgrade

#  upgrade process reimplemented:
#  step 1) unpack RBI or write dd dump directly into booted bank, always
#  step 2)
#    option A) safe, recommended default: delete /overlay for booted bank, prepare_root_runonce for booted bank, prepare_gui_install
#    option B) safest:                    delete /overlay for booted bank, prepare_root_runonce for booted bank
#    option C) unsafe, unless tested:     prepare_migrate_runonce, prepare_gui_install
#    option D) stock, normally hidden:    use stock sysupgrade

#not implemented yet
exit 1