return {
{'UTC_timezone_UTC', 'UTC'},
{'GMT0_timezone_Africa/Abidjan', 'Africa/Abidjan'},
{'GMT0_timezone_Africa/Accra', 'Africa/Accra'},
{'EAT-3_timezone_Africa/Addis Ababa', 'Africa/Addis Ababa'},
{'CET-1_timezone_Africa/Algiers', 'Africa/Algiers'},
{'EAT-3_timezone_Africa/Asmara', 'Africa/Asmara'},
{'GMT0_timezone_Africa/Bamako', 'Africa/Bamako'},
{'WAT-1_timezone_Africa/Bangui', 'Africa/Bangui'},
{'GMT0_timezone_Africa/Banjul', 'Africa/Banjul'},
{'GMT0_timezone_Africa/Bissau', 'Africa/Bissau'},
{'CAT-2_timezone_Africa/Blantyre', 'Africa/Blantyre'},
{'WAT-1_timezone_Africa/Brazzaville', 'Africa/Brazzaville'},
{'CAT-2_timezone_Africa/Bujumbura', 'Africa/Bujumbura'},
{'WET0_timezone_Africa/Casablanca', 'Africa/Casablanca'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Africa/Ceuta', 'Africa/Ceuta'},
{'GMT0_timezone_Africa/Conakry', 'Africa/Conakry'},
{'GMT0_timezone_Africa/Dakar', 'Africa/Dakar'},
{'EAT-3_timezone_Africa/Dar es Salaam', 'Africa/Dar es Salaam'},
{'EAT-3_timezone_Africa/Djibouti', 'Africa/Djibouti'},
{'WAT-1_timezone_Africa/Douala', 'Africa/Douala'},
{'WET0_timezone_Africa/El Aaiun', 'Africa/El Aaiun'},
{'GMT0_timezone_Africa/Freetown', 'Africa/Freetown'},
{'CAT-2_timezone_Africa/Gaborone', 'Africa/Gaborone'},
{'CAT-2_timezone_Africa/Harare', 'Africa/Harare'},
{'SAST-2_timezone_Africa/Johannesburg', 'Africa/Johannesburg'},
{'EAT-3_timezone_Africa/Kampala', 'Africa/Kampala'},
{'EAT-3_timezone_Africa/Khartoum', 'Africa/Khartoum'},
{'CAT-2_timezone_Africa/Kigali', 'Africa/Kigali'},
{'WAT-1_timezone_Africa/Kinshasa', 'Africa/Kinshasa'},
{'WAT-1_timezone_Africa/Lagos', 'Africa/Lagos'},
{'WAT-1_timezone_Africa/Libreville', 'Africa/Libreville'},
{'GMT0_timezone_Africa/Lome', 'Africa/Lome'},
{'WAT-1_timezone_Africa/Luanda', 'Africa/Luanda'},
{'CAT-2_timezone_Africa/Lubumbashi', 'Africa/Lubumbashi'},
{'CAT-2_timezone_Africa/Lusaka', 'Africa/Lusaka'},
{'WAT-1_timezone_Africa/Malabo', 'Africa/Malabo'},
{'CAT-2_timezone_Africa/Maputo', 'Africa/Maputo'},
{'SAST-2_timezone_Africa/Maseru', 'Africa/Maseru'},
{'SAST-2_timezone_Africa/Mbabane', 'Africa/Mbabane'},
{'EAT-3_timezone_Africa/Mogadishu', 'Africa/Mogadishu'},
{'GMT0_timezone_Africa/Monrovia', 'Africa/Monrovia'},
{'EAT-3_timezone_Africa/Nairobi', 'Africa/Nairobi'},
{'WAT-1_timezone_Africa/Ndjamena', 'Africa/Ndjamena'},
{'WAT-1_timezone_Africa/Niamey', 'Africa/Niamey'},
{'GMT0_timezone_Africa/Nouakchott', 'Africa/Nouakchott'},
{'GMT0_timezone_Africa/Ouagadougou', 'Africa/Ouagadougou'},
{'WAT-1_timezone_Africa/Porto-Novo', 'Africa/Porto-Novo'},
{'GMT0_timezone_Africa/Sao Tome', 'Africa/Sao Tome'},
{'EET-2_timezone_Africa/Tripoli', 'Africa/Tripoli'},
{'CET-1_timezone_Africa/Tunis', 'Africa/Tunis'},
{'WAT-1WAST,M9.1.0,M4.1.0_timezone_Africa/Windhoek', 'Africa/Windhoek'},
{'HAST10HADT,M3.2.0,M11.1.0_timezone_America/Adak', 'America/Adak'},
{'AKST9AKDT,M3.2.0,M11.1.0_timezone_America/Anchorage', 'America/Anchorage'},
{'AST4_timezone_America/Anguilla', 'America/Anguilla'},
{'AST4_timezone_America/Antigua', 'America/Antigua'},
{'BRT3_timezone_America/Araguaina', 'America/Araguaina'},
{'ART3_timezone_America/Argentina/Buenos Aires', 'America/Argentina/Buenos Aires'},
{'ART3_timezone_America/Argentina/Catamarca', 'America/Argentina/Catamarca'},
{'ART3_timezone_America/Argentina/Cordoba', 'America/Argentina/Cordoba'},
{'ART3_timezone_America/Argentina/Jujuy', 'America/Argentina/Jujuy'},
{'ART3_timezone_America/Argentina/La Rioja', 'America/Argentina/La Rioja'},
{'ART3_timezone_America/Argentina/Mendoza', 'America/Argentina/Mendoza'},
{'ART3_timezone_America/Argentina/Rio Gallegos', 'America/Argentina/Rio Gallegos'},
{'ART3_timezone_America/Argentina/Salta', 'America/Argentina/Salta'},
{'ART3_timezone_America/Argentina/San Juan', 'America/Argentina/San Juan'},
{'ART3_timezone_America/Argentina/Tucuman', 'America/Argentina/Tucuman'},
{'ART3_timezone_America/Argentina/Ushuaia', 'America/Argentina/Ushuaia'},
{'AST4_timezone_America/Aruba', 'America/Aruba'},
{'PYT4PYST,M10.1.0/0,M4.2.0/0_timezone_America/Asuncion', 'America/Asuncion'},
{'EST5_timezone_America/Atikokan', 'America/Atikokan'},
{'BRT3_timezone_America/Bahia', 'America/Bahia'},
{'AST4_timezone_America/Barbados', 'America/Barbados'},
{'BRT3_timezone_America/Belem', 'America/Belem'},
{'CST6_timezone_America/Belize', 'America/Belize'},
{'AST4_timezone_America/Blanc-Sablon', 'America/Blanc-Sablon'},
{'AMT4_timezone_America/Boa Vista', 'America/Boa Vista'},
{'COT5_timezone_America/Bogota', 'America/Bogota'},
{'MST7MDT,M3.2.0,M11.1.0_timezone_America/Boise', 'America/Boise'},
{'MST7MDT,M3.2.0,M11.1.0_timezone_America/Cambridge Bay', 'America/Cambridge Bay'},
{'AMT4AMST,M10.3.0/0,M2.3.0/0_timezone_America/Campo Grande', 'America/Campo Grande'},
{'CST6CDT,M4.1.0,M10.5.0_timezone_America/Cancun', 'America/Cancun'},
{'VET4:30_timezone_America/Caracas', 'America/Caracas'},
{'GFT3_timezone_America/Cayenne', 'America/Cayenne'},
{'EST5_timezone_America/Cayman', 'America/Cayman'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/Chicago', 'America/Chicago'},
{'MST7MDT,M4.1.0,M10.5.0_timezone_America/Chihuahua', 'America/Chihuahua'},
{'CST6_timezone_America/Costa Rica', 'America/Costa Rica'},
{'AMT4AMST,M10.3.0/0,M2.3.0/0_timezone_America/Cuiaba', 'America/Cuiaba'},
{'AST4_timezone_America/Curacao', 'America/Curacao'},
{'GMT0_timezone_America/Danmarkshavn', 'America/Danmarkshavn'},
{'PST8PDT,M3.2.0,M11.1.0_timezone_America/Dawson', 'America/Dawson'},
{'MST7_timezone_America/Dawson Creek', 'America/Dawson Creek'},
{'MST7MDT,M3.2.0,M11.1.0_timezone_America/Denver', 'America/Denver'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Detroit', 'America/Detroit'},
{'AST4_timezone_America/Dominica', 'America/Dominica'},
{'MST7MDT,M3.2.0,M11.1.0_timezone_America/Edmonton', 'America/Edmonton'},
{'AMT4_timezone_America/Eirunepe', 'America/Eirunepe'},
{'CST6_timezone_America/El Salvador', 'America/El Salvador'},
{'BRT3_timezone_America/Fortaleza', 'America/Fortaleza'},
{'AST4ADT,M3.2.0,M11.1.0_timezone_America/Glace Bay', 'America/Glace Bay'},
{'AST4ADT,M3.2.0/0:01,M11.1.0/0:01_timezone_America/Goose Bay', 'America/Goose Bay'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Grand Turk', 'America/Grand Turk'},
{'AST4_timezone_America/Grenada', 'America/Grenada'},
{'AST4_timezone_America/Guadeloupe', 'America/Guadeloupe'},
{'CST6_timezone_America/Guatemala', 'America/Guatemala'},
{'ECT5_timezone_America/Guayaquil', 'America/Guayaquil'},
{'GYT4_timezone_America/Guyana', 'America/Guyana'},
{'AST4ADT,M3.2.0,M11.1.0_timezone_America/Halifax', 'America/Halifax'},
{'CST5CDT,M3.2.0/0,M10.5.0/1_timezone_America/Havana', 'America/Havana'},
{'MST7_timezone_America/Hermosillo', 'America/Hermosillo'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Indiana/Indianapolis', 'America/Indiana/Indianapolis'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/Indiana/Knox', 'America/Indiana/Knox'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Indiana/Marengo', 'America/Indiana/Marengo'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Indiana/Petersburg', 'America/Indiana/Petersburg'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/Indiana/Tell City', 'America/Indiana/Tell City'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Indiana/Vevay', 'America/Indiana/Vevay'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Indiana/Vincennes', 'America/Indiana/Vincennes'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Indiana/Winamac', 'America/Indiana/Winamac'},
{'MST7MDT,M3.2.0,M11.1.0_timezone_America/Inuvik', 'America/Inuvik'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Iqaluit', 'America/Iqaluit'},
{'EST5_timezone_America/Jamaica', 'America/Jamaica'},
{'AKST9AKDT,M3.2.0,M11.1.0_timezone_America/Juneau', 'America/Juneau'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Kentucky/Louisville', 'America/Kentucky/Louisville'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Kentucky/Monticello', 'America/Kentucky/Monticello'},
{'BOT4_timezone_America/La Paz', 'America/La Paz'},
{'PET5_timezone_America/Lima', 'America/Lima'},
{'PST8PDT,M3.2.0,M11.1.0_timezone_America/Los Angeles', 'America/Los Angeles'},
{'BRT3_timezone_America/Maceio', 'America/Maceio'},
{'CST6_timezone_America/Managua', 'America/Managua'},
{'AMT4_timezone_America/Manaus', 'America/Manaus'},
{'AST4_timezone_America/Marigot', 'America/Marigot'},
{'AST4_timezone_America/Martinique', 'America/Martinique'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/Matamoros', 'America/Matamoros'},
{'MST7MDT,M4.1.0,M10.5.0_timezone_America/Mazatlan', 'America/Mazatlan'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/Menominee', 'America/Menominee'},
{'CST6CDT,M4.1.0,M10.5.0_timezone_America/Merida', 'America/Merida'},
{'CST6CDT,M4.1.0,M10.5.0_timezone_America/Mexico City', 'America/Mexico City'},
{'PMST3PMDT,M3.2.0,M11.1.0_timezone_America/Miquelon', 'America/Miquelon'},
{'AST4ADT,M3.2.0,M11.1.0_timezone_America/Moncton', 'America/Moncton'},
{'CST6CDT,M4.1.0,M10.5.0_timezone_America/Monterrey', 'America/Monterrey'},
{'UYT3UYST,M10.1.0,M3.2.0_timezone_America/Montevideo', 'America/Montevideo'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Montreal', 'America/Montreal'},
{'AST4_timezone_America/Montserrat', 'America/Montserrat'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Nassau', 'America/Nassau'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/New York', 'America/New York'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Nipigon', 'America/Nipigon'},
{'AKST9AKDT,M3.2.0,M11.1.0_timezone_America/Nome', 'America/Nome'},
{'FNT2_timezone_America/Noronha', 'America/Noronha'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/North Dakota/Center', 'America/North Dakota/Center'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/North Dakota/New Salem', 'America/North Dakota/New Salem'},
{'MST7MDT,M3.2.0,M11.1.0_timezone_America/Ojinaga', 'America/Ojinaga'},
{'EST5_timezone_America/Panama', 'America/Panama'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Pangnirtung', 'America/Pangnirtung'},
{'SRT3_timezone_America/Paramaribo', 'America/Paramaribo'},
{'MST7_timezone_America/Phoenix', 'America/Phoenix'},
{'AST4_timezone_America/Port of Spain', 'America/Port of Spain'},
{'EST5_timezone_America/Port-au-Prince', 'America/Port-au-Prince'},
{'AMT4_timezone_America/Porto Velho', 'America/Porto Velho'},
{'AST4_timezone_America/Puerto Rico', 'America/Puerto Rico'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/Rainy River', 'America/Rainy River'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/Rankin Inlet', 'America/Rankin Inlet'},
{'BRT3_timezone_America/Recife', 'America/Recife'},
{'CST6_timezone_America/Regina', 'America/Regina'},
{'AMT4_timezone_America/Rio Branco', 'America/Rio Branco'},
{'PST8PDT,M4.1.0,M10.5.0_timezone_America/Santa Isabel', 'America/Santa Isabel'},
{'BRT3_timezone_America/Santarem', 'America/Santarem'},
{'AST4_timezone_America/Santo Domingo', 'America/Santo Domingo'},
{'BRT3BRST,M10.3.0/0,M2.3.0/0_timezone_America/Sao Paulo', 'America/Sao Paulo'},
{'EGT1EGST,M3.5.0/0,M10.5.0/1_timezone_America/Scoresbysund', 'America/Scoresbysund'},
{'MST7MDT,M3.2.0,M11.1.0_timezone_America/Shiprock', 'America/Shiprock'},
{'AST4_timezone_America/St Barthelemy', 'America/St Barthelemy'},
{'NST3:30NDT,M3.2.0/0:01,M11.1.0/0:01_timezone_America/St Johns', 'America/St Johns'},
{'AST4_timezone_America/St Kitts', 'America/St Kitts'},
{'AST4_timezone_America/St Lucia', 'America/St Lucia'},
{'AST4_timezone_America/St Thomas', 'America/St Thomas'},
{'AST4_timezone_America/St Vincent', 'America/St Vincent'},
{'CST6_timezone_America/Swift Current', 'America/Swift Current'},
{'CST6_timezone_America/Tegucigalpa', 'America/Tegucigalpa'},
{'AST4ADT,M3.2.0,M11.1.0_timezone_America/Thule', 'America/Thule'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Thunder Bay', 'America/Thunder Bay'},
{'PST8PDT,M3.2.0,M11.1.0_timezone_America/Tijuana', 'America/Tijuana'},
{'EST5EDT,M3.2.0,M11.1.0_timezone_America/Toronto', 'America/Toronto'},
{'AST4_timezone_America/Tortola', 'America/Tortola'},
{'PST8PDT,M3.2.0,M11.1.0_timezone_America/Vancouver', 'America/Vancouver'},
{'PST8PDT,M3.2.0,M11.1.0_timezone_America/Whitehorse', 'America/Whitehorse'},
{'CST6CDT,M3.2.0,M11.1.0_timezone_America/Winnipeg', 'America/Winnipeg'},
{'AKST9AKDT,M3.2.0,M11.1.0_timezone_America/Yakutat', 'America/Yakutat'},
{'MST7MDT,M3.2.0,M11.1.0_timezone_America/Yellowknife', 'America/Yellowknife'},
{'ADT3_timezone_America/Atlantic Daylight', 'America/Atlantic Daylight'},
{'AST4_timezone_America/Atlantic Standard', 'America/Atlantic Standard'},
{'AKDT8_timezone_America/Alaska Daylight', 'America/Alaska Daylight'},
{'AKST9_timezone_America/Alaska Standard', 'America/Alaska Standard'},
{'CDT5_timezone_America/Central Daylight', 'America/Central Daylight'},
{'CST6_timezone_America/Central Standard', 'America/Central Standard'},
{'EDT4_timezone_America/Eastern Daylight', 'America/Eastern Daylight'},
{'EST5_timezone_America/Eastern Standard', 'America/Eastern Standard'},
{'EGT1_timezone_America/Eastern Greenland', 'America/Eastern Greenland'},
{'EGST0_timezone_America/Eastern Greenland Summer', 'America/Eastern Greenland Summer'},
{'HADT9_timezone_America/Hawaii-Aleutian Daylight', 'America/Hawaii-Aleutian Daylight'},
{'HAST10_timezone_America/Hawaii-Aleutian Standard', 'America/Hawaii-Aleutian Standard'},
{'HST10_timezone_America/Hawaii Standard', 'America/Hawaii Standard'},
{'MDT6_timezone_America/Mountain Daylight', 'America/Mountain Daylight'},
{'MST7_timezone_America/Mountain Standard', 'America/Mountain Standard'},
{'MeST8_timezone_America/Metlakatla', 'America/Metlakatla'},
{'NDT2:30_timezone_America/Newfoundland Daylight', 'America/Newfoundland Daylight'},
{'NST3:30_timezone_America/Newfoundland Standard', 'America/Newfoundland Standard'},
{'PDT7_timezone_America/Pacific Daylight', 'America/Pacific Daylight'},
{'PST8_timezone_America/Pacific Standard', 'America/Pacific Standard'},
{'PMDT2_timezone_America/Pierre & Miquelon Daylight', 'America/Pierre & Miquelon Daylight'},
{'PMST3_timezone_America/Pierre & Miquelon Standard', 'America/Pierre & Miquelon Standard'},
{'WGT3_timezone_America/Western Greenland', 'America/Western Greenland'},
{'WGST2_timezone_America/Western Greenland Summer', 'America/Western Greenland Summer'},
{'WST-8_timezone_Antarctica/Casey', 'Antarctica/Casey'},
{'DAVT-7_timezone_Antarctica/Davis', 'Antarctica/Davis'},
{'DDUT-10_timezone_Antarctica/DumontDUrville', 'Antarctica/DumontDUrville'},
{'MIST-11_timezone_Antarctica/Macquarie', 'Antarctica/Macquarie'},
{'MAWT-5_timezone_Antarctica/Mawson', 'Antarctica/Mawson'},
{'NZST-12NZDT,M9.5.0,M4.1.0/3_timezone_Antarctica/McMurdo', 'Antarctica/McMurdo'},
{'ROTT3_timezone_Antarctica/Rothera', 'Antarctica/Rothera'},
{'NZST-12NZDT,M9.5.0,M4.1.0/3_timezone_Antarctica/South Pole', 'Antarctica/South Pole'},
{'SYOT-3_timezone_Antarctica/Syowa', 'Antarctica/Syowa'},
{'VOST-6_timezone_Antarctica/Vostok', 'Antarctica/Vostok'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Arctic/Longyearbyen', 'Arctic/Longyearbyen'},
{'AST-3_timezone_Asia/Aden', 'Asia/Aden'},
{'ALMT-6_timezone_Asia/Almaty', 'Asia/Almaty'},
{'ANAT-11ANAST,M3.5.0,M10.5.0/3_timezone_Asia/Anadyr', 'Asia/Anadyr'},
{'AQTT-5_timezone_Asia/Aqtau', 'Asia/Aqtau'},
{'AQTT-5_timezone_Asia/Aqtobe', 'Asia/Aqtobe'},
{'TMT-5_timezone_Asia/Ashgabat', 'Asia/Ashgabat'},
{'AST-3_timezone_Asia/Baghdad', 'Asia/Baghdad'},
{'AST-3_timezone_Asia/Bahrain', 'Asia/Bahrain'},
{'AZT-4AZST,M3.5.0/4,M10.5.0/5_timezone_Asia/Baku', 'Asia/Baku'},
{'ICT-7_timezone_Asia/Bangkok', 'Asia/Bangkok'},
{'EET-2EEST,M3.5.0/0,M10.5.0/0_timezone_Asia/Beirut', 'Asia/Beirut'},
{'KGT-6_timezone_Asia/Bishkek', 'Asia/Bishkek'},
{'BNT-8_timezone_Asia/Brunei', 'Asia/Brunei'},
{'CHOT-8_timezone_Asia/Choibalsan', 'Asia/Choibalsan'},
{'CST-8_timezone_Asia/Chongqing', 'Asia/Chongqing'},
{'IST-5:30_timezone_Asia/Colombo', 'Asia/Colombo'},
{'EET-2EEST,M4.1.5/0,M10.5.5/0_timezone_Asia/Damascus', 'Asia/Damascus'},
{'BDT-6_timezone_Asia/Dhaka', 'Asia/Dhaka'},
{'TLT-9_timezone_Asia/Dili', 'Asia/Dili'},
{'GST-4_timezone_Asia/Dubai', 'Asia/Dubai'},
{'TJT-5_timezone_Asia/Dushanbe', 'Asia/Dushanbe'},
{'EET-2EEST,M3.5.6/0:01,M9.1.5_timezone_Asia/Gaza', 'Asia/Gaza'},
{'CST-8_timezone_Asia/Harbin', 'Asia/Harbin'},
{'ICT-7_timezone_Asia/Ho Chi Minh', 'Asia/Ho Chi Minh'},
{'HKT-8_timezone_Asia/Hong Kong', 'Asia/Hong Kong'},
{'HOVT-7_timezone_Asia/Hovd', 'Asia/Hovd'},
{'IRKT-8IRKST,M3.5.0,M10.5.0/3_timezone_Asia/Irkutsk', 'Asia/Irkutsk'},
{'WIT-7_timezone_Asia/Jakarta', 'Asia/Jakarta'},
{'EIT-9_timezone_Asia/Jayapura', 'Asia/Jayapura'},
{'AFT-4:30_timezone_Asia/Kabul', 'Asia/Kabul'},
{'PETT-11PETST,M3.5.0,M10.5.0/3_timezone_Asia/Kamchatka', 'Asia/Kamchatka'},
{'PKT-5_timezone_Asia/Karachi', 'Asia/Karachi'},
{'CST-8_timezone_Asia/Kashgar', 'Asia/Kashgar'},
{'NPT-5:45_timezone_Asia/Kathmandu', 'Asia/Kathmandu'},
{'IST-5:30_timezone_Asia/Kolkata', 'Asia/Kolkata'},
{'KRAT-7KRAST,M3.5.0,M10.5.0/3_timezone_Asia/Krasnoyarsk', 'Asia/Krasnoyarsk'},
{'MYT-8_timezone_Asia/Kuala Lumpur', 'Asia/Kuala Lumpur'},
{'MYT-8_timezone_Asia/Kuching', 'Asia/Kuching'},
{'AST-3_timezone_Asia/Kuwait', 'Asia/Kuwait'},
{'CST-8_timezone_Asia/Macau', 'Asia/Macau'},
{'MAGT-11MAGST,M3.5.0,M10.5.0/3_timezone_Asia/Magadan', 'Asia/Magadan'},
{'CIT-8_timezone_Asia/Makassar', 'Asia/Makassar'},
{'PHT-8_timezone_Asia/Manila', 'Asia/Manila'},
{'GST-4_timezone_Asia/Muscat', 'Asia/Muscat'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Asia/Nicosia', 'Asia/Nicosia'},
{'NOVT-6NOVST,M3.5.0,M10.5.0/3_timezone_Asia/Novokuznetsk', 'Asia/Novokuznetsk'},
{'NOVT-6NOVST,M3.5.0,M10.5.0/3_timezone_Asia/Novosibirsk', 'Asia/Novosibirsk'},
{'OMST-7_timezone_Asia/Omsk', 'Asia/Omsk'},
{'ORAT-5_timezone_Asia/Oral', 'Asia/Oral'},
{'ICT-7_timezone_Asia/Phnom Penh', 'Asia/Phnom Penh'},
{'WIT-7_timezone_Asia/Pontianak', 'Asia/Pontianak'},
{'KST-9_timezone_Asia/Pyongyang', 'Asia/Pyongyang'},
{'AST-3_timezone_Asia/Qatar', 'Asia/Qatar'},
{'QYZT-6_timezone_Asia/Qyzylorda', 'Asia/Qyzylorda'},
{'MMT-6:30_timezone_Asia/Rangoon', 'Asia/Rangoon'},
{'AST-3_timezone_Asia/Riyadh', 'Asia/Riyadh'},
{'SAKT-10SAKST,M3.5.0,M10.5.0/3_timezone_Asia/Sakhalin', 'Asia/Sakhalin'},
{'UZT-5_timezone_Asia/Samarkand', 'Asia/Samarkand'},
{'KST-9_timezone_Asia/Seoul', 'Asia/Seoul'},
{'CST-8_timezone_Asia/Shanghai', 'Asia/Shanghai'},
{'SGT-8_timezone_Asia/Singapore', 'Asia/Singapore'},
{'CST-8_timezone_Asia/Taipei', 'Asia/Taipei'},
{'UZT-5_timezone_Asia/Tashkent', 'Asia/Tashkent'},
{'GET-4_timezone_Asia/Tbilisi', 'Asia/Tbilisi'},
{'BTT-6_timezone_Asia/Thimphu', 'Asia/Thimphu'},
{'JST-9_timezone_Asia/Tokyo', 'Asia/Tokyo'},
{'ULAT-8_timezone_Asia/Ulaanbaatar', 'Asia/Ulaanbaatar'},
{'CST-8_timezone_Asia/Urumqi', 'Asia/Urumqi'},
{'ICT-7_timezone_Asia/Vientiane', 'Asia/Vientiane'},
{'VLAT-10VLAST,M3.5.0,M10.5.0/3_timezone_Asia/Vladivostok', 'Asia/Vladivostok'},
{'YAKT-9YAKST,M3.5.0,M10.5.0/3_timezone_Asia/Yakutsk', 'Asia/Yakutsk'},
{'YEKT-5YEKST,M3.5.0,M10.5.0/3_timezone_Asia/Yekaterinburg', 'Asia/Yekaterinburg'},
{'AMT-4AMST,M3.5.0,M10.5.0/3_timezone_Asia/Yerevan', 'Asia/Yerevan'},
{'AZOT1AZOST,M3.5.0/0,M10.5.0/1_timezone_Atlantic/Azores', 'Atlantic/Azores'},
{'AST4ADT,M3.2.0,M11.1.0_timezone_Atlantic/Bermuda', 'Atlantic/Bermuda'},
{'WET0WEST,M3.5.0/1,M10.5.0_timezone_Atlantic/Canary', 'Atlantic/Canary'},
{'CVT1_timezone_Atlantic/Cape Verde', 'Atlantic/Cape Verde'},
{'WET0WEST,M3.5.0/1,M10.5.0_timezone_Atlantic/Faroe', 'Atlantic/Faroe'},
{'WET0WEST,M3.5.0/1,M10.5.0_timezone_Atlantic/Madeira', 'Atlantic/Madeira'},
{'GMT0_timezone_Atlantic/Reykjavik', 'Atlantic/Reykjavik'},
{'GST2_timezone_Atlantic/South Georgia', 'Atlantic/South Georgia'},
{'GMT0_timezone_Atlantic/St Helena', 'Atlantic/St Helena'},
{'FKT4FKST,M9.1.0,M4.3.0_timezone_Atlantic/Stanley', 'Atlantic/Stanley'},
{'ACST-9:30ACDT,M10.1.0,M4.1.0/3_timezone_Australia/Adelaide', 'Australia/Adelaide'},
{'AEST-10_timezone_Australia/Brisbane', 'Australia/Brisbane'},
{'ACST-9:30ACDT,M10.1.0,M4.1.0/3_timezone_Australia/Broken Hill', 'Australia/Broken Hill'},
{'AEST-10AEDT,M10.1.0,M4.1.0/3_timezone_Australia/Currie', 'Australia/Currie'},
{'ACST-9:30_timezone_Australia/Darwin', 'Australia/Darwin'},
{'CWST-8:45_timezone_Australia/Eucla', 'Australia/Eucla'},
{'AEST-10AEDT,M10.1.0,M4.1.0/3_timezone_Australia/Hobart', 'Australia/Hobart'},
{'AEST-10_timezone_Australia/Lindeman', 'Australia/Lindeman'},
{'LHST-10:30LHDT-11,M10.1.0,M4.1.0_timezone_Australia/Lord Howe', 'Australia/Lord Howe'},
{'AEST-10AEDT,M10.1.0,M4.1.0/3_timezone_Australia/Melbourne', 'Australia/Melbourne'},
{'AWST-8_timezone_Australia/Perth', 'Australia/Perth'},
{'AEST-10AEDT,M10.1.0,M4.1.0/3_timezone_Australia/Sydney', 'Australia/Sydney'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Amsterdam', 'Europe/Amsterdam'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Andorra', 'Europe/Andorra'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Athens', 'Europe/Athens'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Belgrade', 'Europe/Belgrade'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Berlin', 'Europe/Berlin'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Bratislava', 'Europe/Bratislava'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Brussels', 'Europe/Brussels'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Bucharest', 'Europe/Bucharest'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Budapest', 'Europe/Budapest'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Chisinau', 'Europe/Chisinau'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Copenhagen', 'Europe/Copenhagen'},
{'GMT0IST,M3.5.0/1,M10.5.0_timezone_Europe/Dublin', 'Europe/Dublin'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Gibraltar', 'Europe/Gibraltar'},
{'GMT0BST,M3.5.0/1,M10.5.0_timezone_Europe/Guernsey', 'Europe/Guernsey'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Helsinki', 'Europe/Helsinki'},
{'GMT0BST,M3.5.0/1,M10.5.0_timezone_Europe/Isle of Man', 'Europe/Isle of Man'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Istanbul', 'Europe/Istanbul'},
{'GMT0BST,M3.5.0/1,M10.5.0_timezone_Europe/Jersey', 'Europe/Jersey'},
{'EET-2EEST,M3.5.0,M10.5.0/3_timezone_Europe/Kaliningrad', 'Europe/Kaliningrad'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Kiev', 'Europe/Kiev'},
{'WET0WEST,M3.5.0/1,M10.5.0_timezone_Europe/Lisbon', 'Europe/Lisbon'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Ljubljana', 'Europe/Ljubljana'},
{'GMT0BST,M3.5.0/1,M10.5.0_timezone_Europe/London', 'Europe/London'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Luxembourg', 'Europe/Luxembourg'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Madrid', 'Europe/Madrid'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Malta', 'Europe/Malta'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Mariehamn', 'Europe/Mariehamn'},
{'EET-2EEST,M3.5.0,M10.5.0/3_timezone_Europe/Minsk', 'Europe/Minsk'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Monaco', 'Europe/Monaco'},
{'MSK-4_timezone_Europe/Moscow', 'Europe/Moscow'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Oslo', 'Europe/Oslo'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Paris', 'Europe/Paris'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Podgorica', 'Europe/Podgorica'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Prague', 'Europe/Prague'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Riga', 'Europe/Riga'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Rome', 'Europe/Rome'},
{'SAMT-3SAMST,M3.5.0,M10.5.0/3_timezone_Europe/Samara', 'Europe/Samara'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/San Marino', 'Europe/San Marino'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Sarajevo', 'Europe/Sarajevo'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Simferopol', 'Europe/Simferopol'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Skopje', 'Europe/Skopje'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Sofia', 'Europe/Sofia'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Stockholm', 'Europe/Stockholm'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Tallinn', 'Europe/Tallinn'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Tirane', 'Europe/Tirane'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Uzhgorod', 'Europe/Uzhgorod'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Vaduz', 'Europe/Vaduz'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Vatican', 'Europe/Vatican'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Vienna', 'Europe/Vienna'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Vilnius', 'Europe/Vilnius'},
{'VOLT-3VOLST,M3.5.0,M10.5.0/3_timezone_Europe/Volgograd', 'Europe/Volgograd'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Warsaw', 'Europe/Warsaw'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Zagreb', 'Europe/Zagreb'},
{'EET-2EEST,M3.5.0/3,M10.5.0/4_timezone_Europe/Zaporozhye', 'Europe/Zaporozhye'},
{'CET-1CEST,M3.5.0,M10.5.0/3_timezone_Europe/Zurich', 'Europe/Zurich'},
{'EAT-3_timezone_Indian/Antananarivo', 'Indian/Antananarivo'},
{'IOT-6_timezone_Indian/Chagos', 'Indian/Chagos'},
{'CXT-7_timezone_Indian/Christmas', 'Indian/Christmas'},
{'CCT-6:30_timezone_Indian/Cocos', 'Indian/Cocos'},
{'EAT-3_timezone_Indian/Comoro', 'Indian/Comoro'},
{'TFT-5_timezone_Indian/Kerguelen', 'Indian/Kerguelen'},
{'SCT-4_timezone_Indian/Mahe', 'Indian/Mahe'},
{'MVT-5_timezone_Indian/Maldives', 'Indian/Maldives'},
{'MUT-4_timezone_Indian/Mauritius', 'Indian/Mauritius'},
{'EAT-3_timezone_Indian/Mayotte', 'Indian/Mayotte'},
{'RET-4_timezone_Indian/Reunion', 'Indian/Reunion'},
{'WST11_timezone_Pacific/Apia', 'Pacific/Apia'},
{'NZST-12NZDT,M9.5.0,M4.1.0/3_timezone_Pacific/Auckland', 'Pacific/Auckland'},
{'CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45_timezone_Pacific/Chatham', 'Pacific/Chatham'},
{'VUT-11_timezone_Pacific/Efate', 'Pacific/Efate'},
{'PHOT-13_timezone_Pacific/Enderbury', 'Pacific/Enderbury'},
{'TKT10_timezone_Pacific/Fakaofo', 'Pacific/Fakaofo'},
{'FJT-12_timezone_Pacific/Fiji', 'Pacific/Fiji'},
{'TVT-12_timezone_Pacific/Funafuti', 'Pacific/Funafuti'},
{'GALT6_timezone_Pacific/Galapagos', 'Pacific/Galapagos'},
{'GAMT9_timezone_Pacific/Gambier', 'Pacific/Gambier'},
{'SBT-11_timezone_Pacific/Guadalcanal', 'Pacific/Guadalcanal'},
{'ChST-10_timezone_Pacific/Guam', 'Pacific/Guam'},
{'HST10_timezone_Pacific/Honolulu', 'Pacific/Honolulu'},
{'HST10_timezone_Pacific/Johnston', 'Pacific/Johnston'},
{'LINT-14_timezone_Pacific/Kiritimati', 'Pacific/Kiritimati'},
{'KOST-11_timezone_Pacific/Kosrae', 'Pacific/Kosrae'},
{'MHT-12_timezone_Pacific/Kwajalein', 'Pacific/Kwajalein'},
{'MHT-12_timezone_Pacific/Majuro', 'Pacific/Majuro'},
{'MART9:30_timezone_Pacific/Marquesas', 'Pacific/Marquesas'},
{'SST11_timezone_Pacific/Midway', 'Pacific/Midway'},
{'NRT-12_timezone_Pacific/Nauru', 'Pacific/Nauru'},
{'NUT11_timezone_Pacific/Niue', 'Pacific/Niue'},
{'NFT-11:30_timezone_Pacific/Norfolk', 'Pacific/Norfolk'},
{'NCT-11_timezone_Pacific/Noumea', 'Pacific/Noumea'},
{'SST11_timezone_Pacific/Pago Pago', 'Pacific/Pago Pago'},
{'PWT-9_timezone_Pacific/Palau', 'Pacific/Palau'},
{'PST8_timezone_Pacific/Pitcairn', 'Pacific/Pitcairn'},
{'PONT-11_timezone_Pacific/Ponape', 'Pacific/Ponape'},
{'PGT-10_timezone_Pacific/Port Moresby', 'Pacific/Port Moresby'},
{'CKT10_timezone_Pacific/Rarotonga', 'Pacific/Rarotonga'},
{'ChST-10_timezone_Pacific/Saipan', 'Pacific/Saipan'},
{'TAHT10_timezone_Pacific/Tahiti', 'Pacific/Tahiti'},
{'GILT-12_timezone_Pacific/Tarawa', 'Pacific/Tarawa'},
{'TOT-13_timezone_Pacific/Tongatapu', 'Pacific/Tongatapu'},
{'TRUT-10_timezone_Pacific/Truk', 'Pacific/Truk'},
{'WAKT-12_timezone_Pacific/Wake', 'Pacific/Wake'},
{'WFT-12_timezone_Pacific/Wallis', 'Pacific/Wallis'},}
