#!/bin/sh

config_load mmpbx

config_get_bool enabled global enabled 0
[ $enabled -eq 0 ] && exit 0

local iface0=$(uci -q get mmpbxrvsipnet.@network[0].interface)
local iface1=$(uci -q get mmpbxrvsipnet.@network[1].interface)

[ "$INTERFACE" = "$iface0" ] || [ "$INTERFACE" = "$iface1" ] && [ "$ACTION" = "ifup" ] && /etc/init.d/mmpbxd reload
